### ISSUE TITLE
`dotnet code-coverage` and multi-targeting projects

### ISSUE THREAD

**Issue by RussKie** [microsoft/codecoverage#10]
After switching to `dotnet code-coverage "command"` from `dotnet test --collect:... --test-adapter-path:...` I'm observing the resulting cobertura.xml to have a lot of duplication, which in our case leads to 400% increase in size - from 5MB to 25MB. Our projects target multiple TFMs (up to 7 in worse scenarios), and the code coverage data is duplicated. Previously, when I collected the coverage with `dotnet test` and then merged individual results, the resulting coverage was de-duplicated.

You can grab the `dotnet code-coverage` cobertura.xml [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=2124110&view=artifacts&pathAsName=false&type=publishedArtifacts) (under "drop").
The `dotnet test` merged covertura.xml can be downloaded from [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=2120222&view=artifacts&pathAsName=false&type=publishedArtifacts) (under "drop"). 

Not sure about best way forward here. Perhaps the following would work:
1. Remove complete dups of `package` node (a dup means all data is the same).
2. If `package` node's data is different - then report is per TFM

For example:
```xml
<!-- coverage is different per TFM -->
<package name="PackageA" target-framework="net8.0" line-rate="1" branch-rate="1" complexity="41">...</package>
<package name="PackageA" target-framework="net472" line-rate="0.955" branch-rate="0.88" complexity="41">...</package>

<!-- coverage is the same across all TFMs -->
<package name="PackageB" line-rate="1" branch-rate="1" complexity="41">...</package>
```

**Comment by jakubch1** [comment]
Please try latest 17.6.7. We added logic to not duplicate stuff for cobertura report. Each project even with more target frameworks should be only once in final report now. We can't add `target-framework="net8.0"` because it is breaking cobertura format. Report generator, codecov.io etc would not understand it. If you need separate entry for each target framework I recommend change binary file name to for example `library.net48.dll`.

**Comment by RussKie** [comment]
Sounds good, thank you.
