### ISSUE TITLE
Microsoft.Coverage as default in Test project

### ISSUE THREAD

**Issue by darthkurak** [microsoft/codecoverage#109]
Right now if you create a new tests project - coverlet.collector is added as default.
Is there any plan to change this to Microsoft.Coverage?

**Comment by Evangelink** [comment]
Hi @darthkurak,

Please refer and follow this issue https://github.com/dotnet/test-templates/issues/355. We do plan to make Microsoft CodeCoverage the default for MSTest and make it an option for NUnit and xUnit.

@fhnaseer You can close this issue.
