### ISSUE TITLE
Issue with Microsoft.CodeCoverage.Analysis

### ISSUE THREAD

**Issue by XJPan-Jeff** [microsoft/codecoverage#116]
Hello,

I am measuring the code coverage of a huge desktop app which is written mainly in C++.

[Problem Conext] The basic workflow -
1. Instrument DLLs via vsinstr.exe
2. Start VSPerfMon via VSPerfCmd
3. Run test cases
4. Stop VSPerfMon and un-instrument DLLs
5. Convert the binary coverage file to XML,  via a home-grown program
6. Generate coverage report via tool from https://github.com/danielpalme/ReportGenerator

Probem is with step 5 above.  We wrote this program following https://github.com/danielpalme/ReportGenerator/wiki/Visual-Studio-Coverage-Tools a few years ago. We referenced Microsoft.VisualStudio.Coverage.Analysis.dll, Microsoft.VisualStudio.Coverage.Interop.dll and Microsoft.VisualStudio.Coverage.Symbols.dll in version 14.0.2.

Problem 1:
The program runs out of memory if it is to convert a coverage file > 1.2 GB.  As my checking, those DLLs are 32bit based, so I doubt they are limited in memory comsumption.

Problem #2:
Recently I am updating the program with new DLLs in v17.0,  but with slight different names: [Uploading CodeCoverage.zip…](), Microsoft.CodeCoverage.IO.dll, Microsoft.Internal.VisualStudio.Interop.dll and Microsoft.VisualStudio.Coverage.Symbols.dll.
There are 2 problems -
2.1  The program can run but quit with alert that it can't load the correct DLL for symbol parsing
2.2  So I put in the Microsoft.VisualStudio.Coverage.Symbols.dll v14 again. The program runs but never returns,  it hangs. 

Can you please help check the issues above?  I am hoping to continue the workflow and tools,  with the capability to convert large coverage binaries. Many thanks!

Thanks,
Jeff

**Comment by fhnaseer** [comment]
Microsoft.CodeCoverage.IO is obsolete and is no longer maintained. However Microsoft.CodeCoverage.Analaysis is shipped with latest VS and is also available [here](https://dev.azure.com/dnceng/public/_artifacts/feed/test-tools/NuGet/Microsoft.CodeCoverage.Analysis/overview/17.11.0). You can use `AnalysisCoverageFileUtility` to merge (convert) report to xml format. Please note that these are internal tools and you are using it at your own risk. We can break public APIs in future releases.

I would also like you to explore [Microsoft.CodeCoverage.Console tool](https://learn.microsoft.com/en-us/visualstudio/test/microsoft-code-coverage-console-tool?view=vs-2022) to instrument and calculate code coverage for C++ applications.

**Comment by XJPan-Jeff** [comment]
Many thanks @fhnaseer !

1. With the AS-IS process,  I tried AnalysisCoverageFileUtility in the new Microsoft.CodeCoverage.Analaysis but it reported that the coverage file is not in valid format. It looks the dll does not recognize the output from VSPerfMon.

2.  Then I tried Microsoft.CodeCoverage.Console tool with server mode, but I am blocked at the instrument step.  I am sure I have built my application with the linker option /PROFILE,  then I can instrument small DLL like in 10+MB size but I can't instrument bigger DLLs with error message "Link with the /PROFILE linker swith, ensure FASTLINK is disabled, and that the PDBis writable". The tool looks quite dependent on the DLL size.

So, neither resolved my problems... Any further insight?

**Comment by fhnaseer** [comment]
1. Can you please share your coverage file? 

2. Can you please enable logs for the instrumentation command and share these?

Console tool cannot understand VSPerfMon coverage format but it should be able to understand report generated using server mode.

**Comment by XJPan-Jeff** [comment]
1.  Attached please find one sample coverage file from VSPerfMon. 
[custom_coverage.zip](https://github.com/microsoft/codecoverage/files/15073711/custom_coverage.zip)

2. Attached please find the log of instrumentation command - I tried to instrument a couple of DLLs. The log looks quite trival.
[instrument.log](https://github.com/microsoft/codecoverage/files/15073757/instrument.log)

**Comment by fhnaseer** [comment]
1. Can you please confirm that original dlls and pdbs are present in the same folder as of coverage file?

2. Can you please confirm that following things for instrumentation.
2.1. /PROFILE is set
2.2. <GenerateDebugInformation>DebugFull</GenerateDebugInformation> full debug info
2.3. Make sure also debug information for all dependent static libraries are available
2.4. pdb is available when instrument command is called

**Comment by fhnaseer** [comment]
1. Folder looks fine. Though you are using an older version of Microsoft.CodeCoverage.Analysis. Please use 17.11 or later.
```
var utility = new AnalysisCoverageFileUtility(coverageFileConfiguration);
utility.ReadCoverageReportAsync(path, cancellationToken);
```
For 2, can you please create an issue here https://developercommunity.visualstudio.com.

**Comment by XJPan-Jeff** [comment]
I am consulting the security team in my organization about the compliance to share the PDBs. Will let you know soon. 

BTW, according to https://stackoverflow.com/questions/24451827/programmatically-convert-coverage-file-to-coveragexml?newreg=4171eec4cb6649bb96b9ac6989963cf1, there seems x64 build of analysis and interops DLL in lower version like v14. 

Is there any chance to get the x64 DLLs?

**Comment by fhnaseer** [comment]
The API and package mentioned here is very old. CC.Analysis 17.11.0 package contains both x86 and x64 dlls. So, it should be able to open large files without giving memory exception. I tried to open your coverage file. It seemed to be a correct coverage file, but it was not able to find original dlls and pdbs and hence it was giving exception.

> I am consulting the security team in my organization about the compliance to share the PDBs. Will let you know soon.
> 
> BTW, according to https://stackoverflow.com/questions/24451827/programmatically-convert-coverage-file-to-coveragexml?newreg=4171eec4cb6649bb96b9ac6989963cf1, there seems x64 build of analysis and interops DLL in lower version like v14.
> 
> Is there any chance to get the x64 DLLs?

**Comment by XJPan-Jeff** [comment]
Add the dll / pdb and coverage binary to https://developercommunity.visualstudio.com/t/Cant-instrument-DLLs-using-MicrosoftCo/10645886?viewtype=all&moreInfo=true.

**Comment by fhnaseer** [comment]
Closing this ticket. Follow here => https://developercommunity.visualstudio.com/t/Cant-instrument-DLLs-using-MicrosoftCo/10645886#T-ND10661701
