### ISSUE TITLE
Question: How to get test coverage from a remote running .NET server/session?

### ISSUE THREAD

**Issue by sahinM** [microsoft/codecoverage#119]
I am referring to the [scenario15](https://github.com/microsoft/codecoverage/tree/main/samples/Calculator/scenarios/scenario15) of the Calculator sample application in the documentation.
In the doc of [Sample scenarios](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-coverage#sample-scenarios), moreover in the chapter [Sessions](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-coverage#sessions) you are describing very well how to:

1. Start the code coverage collection with the session **scenario-x** in the background and in server-mode, and providing the config e.g. output directory and format.
2. Start **webapp-x** by connecting to that given session-id- a session-id and the `dotnet run` command.
3. Run your `dotnet test`command within the 
4. Shutdown and close your session / server

but let's say, given:
* a `session-id`: **scenario-x**
* an ASP NET Core web application: **webapp-x** running on a different machine (e.g. a K8s pod on a namespace webapps) and is exposed with a public IP address within a VNET to restrict access by (e.g. an Agent, which is running integration and e2e tests against this app).
* integration tests: **tests-x** triggered again on a another machine (e.g. an agent running an Azure DevOps YAML pipeline) which also is interested to get the code coverage to e.g. push the test results to SonarCloud.

Is it possible to to accomplish that? Can **test-x** and **webapp-x** connect to the **scenario-x**, to exchange code coverage?

In the documentation you are "connecting" to this "session" via the `session-id`. But does this only work if they are on the same machine? Is there any way to run and collect test coverage of a remotely running application?
I am planning to run e2e tests against a running application running on a different machine, and I was assuming that exactly this server mode feature of the dotnet coverage tool provides this.

Thanks in advance 😄.

**Comment by fhnaseer** [comment]
At this moment we only support coverage collection on a single machine.

Similar feature is requested [here](https://github.com/microsoft/codecoverage/issues/103), so I am closing this as duplicate.
