### ISSUE TITLE
No blocks covered using static instrumentation

### ISSUE THREAD

**Issue by KavenBreton-eaton** [microsoft/codecoverage#120]
Hello,

Since we have a lot of Windows services running from which we want to gather code coverage, we decided to instrument all our binaries using
`dotnet-coverage instrument -s "C:\dev\localCoverageTest\codecoverage.runsettings" -id "Project.CodeCoverage" "c:\file\path"`
We are then starting collection using
`dotnet-coverage collect -id "Project.CodeCoverage" --server-mode -s "C:\dev\localCoverageTest\codecoverage.runsettings"`
Our runsettings file looks like this
`<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
        <Configuration>
          <CoverageLogLevel>All</CoverageLogLevel>
          <InstrumentationLogLevel>All</InstrumentationLogLevel>
          <ManagedVanguardLogLevel>Info</ManagedVanguardLogLevel>
          <CoverageFileLogPath>C:\dev\localCoverageTest\dotnet-coverage-collect.log</CoverageFileLogPath>
          <CoverageFileName>C:\dev\localCoverageTest\fam.coverage</CoverageFileName>
          <Format>coverage</Format>
          <CodeCoverage>
            
            
            
            
            <AllowLowIntegrityProcesses>True</AllowLowIntegrityProcesses>
            <SymbolsRestrictOriginalPathAccess>True</SymbolsRestrictOriginalPathAccess>
            <SymbolsRestrictReferencePathAccess>True</SymbolsRestrictReferencePathAccess>
            
            
            <EnableDynamicNativeInstrumentation>False</EnableDynamicNativeInstrumentation>
            <EnableStaticNativeInstrumentation>False</EnableStaticNativeInstrumentation>
            <EnableStaticNativeInstrumentationRestore>False</EnableStaticNativeInstrumentationRestore>
            <EnableDynamicManagedInstrumentation>False</EnableDynamicManagedInstrumentation>
            <EnableStaticManagedInstrumentation>True</EnableStaticManagedInstrumentation>
            <EnableStaticManagedInstrumentationRestore>True</EnableStaticManagedInstrumentationRestore>
            <SymbolSearchPaths>
              <Path>C:\dev\GitHub\etn-utilities\fam-solution\bin\Release\pdb</Path>
            </SymbolSearchPaths>
            <DumpStaticNativeDisassembly>False</DumpStaticNativeDisassembly>
            <FileLogPath>C:\dev\localCoverageTest\file-log.log</FileLogPath>
            <LogLevel>All</LogLevel>
          </CodeCoverage>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>`
When loading the resulting .coverage file, I can see a bunch of blocks detected but nothing was covered.
[dotnet-coverage-collect.log](https://github.com/microsoft/codecoverage/files/15325509/dotnet-coverage-collect.log)

Am I missing something in the logs that could indicate the problem?

**Comment by KavenBreton-eaton** [comment]
I forgot to add that our project is in C# .NET Framework 4.8

**Comment by fhnaseer** [comment]
Is this the same service you mentioned here? https://github.com/microsoft/codecoverage/issues/96

From the logs, I can see that dlls are being loaded and eventually added in the final report. Can you please check if server and service are running under same credentials? Administrator mode?

**Comment by KavenBreton-eaton** [comment]
Yes, same as #96 
I think it might be related to the user since our services are running under Local System. Is it possible to do or would I have to make our services run under another user? Do they both need to be in Administrator mode?

**Comment by KavenBreton-eaton** [comment]
After more testing, I was able to get coverage from our client application but not our services. Even if I make our services runs as the same user, I never get a block covered for them. I also tried starting the collection in a not elevated command prompt.

**Comment by fhnaseer** [comment]
Do you have VS Enterprise? If yes, then can you please try using Microsoft.CodeCoverage.Console.exe from VS? It has same commands as dotnet-coverage
https://learn.microsoft.com/en-us/visualstudio/test/microsoft-code-coverage-console-tool?view=vs-2022

**Comment by KavenBreton-eaton** [comment]
I am going to test it. Is there anything really different from dotnet-coverage itsefl?

**Comment by fhnaseer** [comment]
Microsoft.CodeCoverage.Console.exe is built against net framework while dotnet-coverage is net core.

This could be because of security features available in net framework but not available in net core.

**Comment by KavenBreton-eaton** [comment]
https://learn.microsoft.com/en-us/answers/questions/1470826/how-do-i-use-microsoft-codecoverage-console-exe-in
It was asked here but it seems like I won't be able to use that tool on our test VMs anyway. Is it worth trying anyway?

**Comment by fhnaseer** [comment]
> https://learn.microsoft.com/en-us/answers/questions/1470826/how-do-i-use-microsoft-codecoverage-console-exe-in It was asked here but it seems like I won't be able to use that tool on our test VMs anyway. Is it worth trying anyway?

You can use it if you install dotnet framework on VM.

**Comment by KavenBreton-eaton** [comment]
Thank you. Using the Microsoft CodeCoverage console allowed us to gather the coverage from our services.
