### ISSUE TITLE
Add --nologo option

### ISSUE THREAD

**Issue by tomap** [microsoft/codecoverage#126]
Hello,

Would it be possible to have a nologo argument to the command line ?

Just like for dotnet test https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test

That would remove this from output:

```
Microsoft (R) Code Coverage Command Line Tool (x64)
Copyright (c) Microsoft Corporation. All rights reserved.
```

Thank you

**Comment by fhnaseer** [comment]
`--nologo` option has been added and will be available in the next release of `dotnet-coverage`.
