### ISSUE TITLE
Calling `dotnet-coverage collect` with invalid or non-existing settings file does not show error

### ISSUE THREAD

**Issue by StefH** [microsoft/codecoverage#128]
Calling this:
``` ps
dotnet-coverage collect -s "does-not-exists" -f cobertura -o "file.xml" "dotnet test ./test.csproj --no-build"
```

Does **not** show error when the settings file is invalid or non-existing.

**Comment by fhnaseer** [comment]
This has been implemented and console will write warning if config file is invalid or missing. It will be available in the next release 17.12.0.
