### ISSUE TITLE
dotnet-coverage merge marks cobertura files as invalid when different keyboard/OS language is being used

### ISSUE THREAD

**Issue by CssaBee** [microsoft/codecoverage#130]
Using even the sample from https://gcovr.com/en/stable/output/cobertura.html, 'dotnet-coverage merge' marks it as an invalid file.
Changing all the dots to commas (representing numbers, e.g. 5.0 vs 5,0) suddenly everything starts to work again.

Using the tool should be language independent and parse cobertura files using dots only for number representation.

AB#2242145

**Comment by fhnaseer** [comment]
This has been fixed and will be available in the next release.
