### ISSUE TITLE
Instrumentation with Microsoft.CodeCoverage.console.exe causes program to crash with segmentation fault or behave different

### ISSUE THREAD

**Issue by dhoelzl** [microsoft/codecoverage#144]
When instrumenting DLLs loaded by an executable (all native C and C++) with `Microsoft.CodeCoverage.console.exe` it stops working and crashes reproducibly with a segementation fault every time it’s launched and a specific execution path is taken. It’s also reproducible that the instrumented code behaves different than expected in another situtation.
The situation would also be reproducible if the executable is statically linked and the executable is instrumented instead of the DLL as in this example, so I assume that the fact that DLLs are instrumented is not the root cause of the problem. The problem only occurs in parts of our instrumented code, not all programs / execution paths seem to be affected - if not affected, everything including recording of code coverage works as expected.

Reproduction: See `README.tx`t in attached file:

[coverage_problems.zip](https://aka.ms/dc/file?name=B861bd9ca510043409f2553a28389f373638676040403171065_coverage_problems.zip&tid=861bd9ca510043409f2553a28389f373638676040403171065)

Also see https://developercommunity.visualstudio.com/t/Problem-Report:-Instrumentation-with-Mic/10793811

```
Microsoft.CodeCoverage.console.exe --version
17.10.4+a12555c42042c92e5c5c12399e7ab27a3fec615c
```

**Comment by fhnaseer** [comment]
Can you please try this on VS 17.12?

**Comment by dhoelzl** [comment]
Looks like it works with VS 17.12, thank you!
