### ISSUE TITLE
Question - Branch Coverage and supported 'dotnet-coverage collect' formats (xml vs. cobertura)?

### ISSUE THREAD

**Issue by pmehradnia** [microsoft/codecoverage#147]
[dotnet-coverage collect](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-coverage#dotnet-coverage-collect) has the following three format options (with "--output-format"):

- coverage
- xml
- cobertura

From some testing, it appears that Branch Coverage* is only produced with the _cobertura_ option (not _xml_). Is there an option to enable Branch Coverage for the xml format, or is it exclusive to cobertura format?

Thanks in advance.

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- 

_*Note: For reference, example file showing branch coverage data (from ~\codecoverage\samples\Algorithms\scenarios\scenario01\example.report.cobertura.xml)_

![Image](https://github.com/user-attachments/assets/f62c8479-6727-4939-8e65-9324e9b4b627)

**Comment by fhnaseer** [comment]
Branch coverage is specific to cobertura format. In xml/coverage format there is block coverage. If all blocks are not covered for a line, line coverage status will be partially covered.

![Image](https://github.com/user-attachments/assets/76785b81-55b4-4053-abbb-7e548acaa666)

**Comment by pmehradnia** [comment]
> Branch coverage is specific to cobertura format. In xml/coverage format there is block coverage. If all blocks are not covered for a line, line coverage status will be partially covered.
> 
> ![Image](https://github.com/user-attachments/assets/76785b81-55b4-4053-abbb-7e548acaa666)

Thank you for your reply. Is this information specified on a documentation somewhere, as far as you know, for the xml or coverage formats?

**Comment by fhnaseer** [comment]
There is no official documentation about coverage and xml format. They both contain same data (one is in xml, other not).

**Comment by pmehradnia** [comment]
> There is no official documentation about coverage and xml format. They both contain same data (one is in xml, other not).

Got it - so the only format which has the branch coverage would be cobertura. Thanks for your help.
