### ISSUE TITLE
Can't get correct .coverage report file with win22/20221204.3

### ISSUE THREAD

**Issue by Darwin-Li-001** [microsoft/codecoverage#15]
## Description
**Do unit test with "windows-2022" in Azure pipeline**.
![image](https://user-images.githubusercontent.com/57886721/212242409-94d6d655-8260-4365-8621-6b680699b7c9.png)

The result was always correct before, but since the agent upgrade to version 20221204.3, we **can't get Unit Test coverage correctly**.
And the size of .coverage file is not as big as normal.
please help to have a debug. Thanks!

## Steps to reproduce

1.Run unit test with VS test (agent windows-2022)  in Azure pipeline;
2.Try to get the unit test coverage.

## Expected behavior
correct *.coverage file about about few hundred K bytes should be got.

## Actual behavior
The *.coverage file is to small. only about 23K.
![image](https://user-images.githubusercontent.com/57886721/212243018-07544a13-5d68-40d4-a8e1-4bfb740c87ca.png)

## Environment
 Azure DevOps
 Windows Server 2022

**Comment by jakubch1** [comment]
@Darwin-Li-001 any update on this? Were you able to test it using latest TestPlatform and coverage packages?
