### ISSUE TITLE
XML conversion yields incorrect COVERAGE result values.

### ISSUE THREAD

**Issue by kahuz** [microsoft/codecoverage#18]
## Environment
Windows 10 21H2 enterprise
Visual Studio 2019 16.11.24 enterprise
vstest 16.11.0
CodeCoverage 16.0.21270.227002

## Issue
We've noticed that the code coverage analysis provided by Visual Studio 2019 Enterprise results in different coverage measurements when converted to xml by the CodeCoverage tool.

In order to interpret the issue situation with the same configuration values, the example below shows a comparison of the code coverage measurement results of Visual Studio 2019 and VSTest.
- Visual Studio and VSTest use the runsettings configuration file.
- For CodeCoverage, we use the config configuration.
- Note that runsettings and config use the same <CodeCoverage> property when measuring code coverage, but we excluded it from the comparison for an accurate comparison.

### Measuring Visual Studio 2019 Code Coverage
![image](https://user-images.githubusercontent.com/67911543/224580650-15348e3d-1b07-42ec-99ff-6eb41ea45177.png)
- As a result, the covered/not-covered range for block coverage can be obtained as above.(visual.gtest.coverage)

![image](https://user-images.githubusercontent.com/67911543/224580755-a7882cca-f199-498f-9ddd-e5a1e45c6b15.png)
- Can see that the xml output stores the same results as Visual Studio.

### Measuring VSTest Code Coverage
I measured code coverage with VSTest in the CLI as follows.
```powershell
vstest.console.exe' .\test\Release\x64\gtest.exe /Platform:x64 /TestAdapterPath:.\packages\GoogleTestAdapter.0.18.0\build\_common /EnableCodeCoverage /ResultsDirectory:".\data\CodeCoverage\VSTest Result" /Settings:.\test\coverage\CodeCoverage.runsettings
```
![image](https://user-images.githubusercontent.com/67911543/224580910-02340f4d-80b9-45c9-9e01-7654f46e203c.png)
- When I checked the generated output in Visual Studio, I saw the same results.

convert the above result to xml using the CodeCoverage tool, it seems that the inspection result value is stored incorrectly as shown below.

```powershell
CodeCoverage.exe' analyze /output:"data\CodeCoverage\CodeCoverage Result\gtest.exe.coverage.xml" "data\CodeCoverage\CodeCoverage Result\vstest.gtest.coverage"
```
- Generate xml.

![image](https://user-images.githubusercontent.com/67911543/224581201-cfd0a672-856b-4131-89b7-81d7f1dce5e8.png)
- XML conversion result with CodeCoverage (vstest.gtest.coverage.xml)

![image](https://user-images.githubusercontent.com/67911543/224581345-488bc20b-a093-47e0-b442-e73c48ef6c14.png)
- Results of xml conversion of vstest.gtest.coverage in Visual Studio.

**Comment by fhnaseer** [comment]
@kahuz We use two different algorithms to calculate coverage numbers when showing in Visual Studio and converting it to xml file. That's why you are seeing different numbers. In next release of Visual Studio we have fixed this issue.

**Comment by kahuz** [comment]
@fhnaseer Thanks for answering my question 😃
