### ISSUE TITLE
[Runsettigns] Path separator used in ModulePath is OS-sensitive 

### ISSUE THREAD

**Issue by stan-sz** [microsoft/codecoverage#2]
A path separator (either `\\` or `/`) used in `Include`'s or `Exclude`'s `<ModulePath>` will make the path to be specific to a particular OS and as a result the .runsettings file may return different results on different OS. Given that `ModulePath` is already case-agnostic, having it path separator-agnostic would be beneficial. If this is not possible, issue a warning.

**Comment by jakubch1** [comment]
@MarcoRossignoli WDYT? Is there some generic way to handle it in .NET world? How this is done in coverlet? Do you exclude by filename only or whole path?

**Comment by MarcoRossignoli** [comment]
In coverlet we don't do nothing special https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.collector/DataCollection/CoverletSettingsParser.cs#L31 we take it as-is 

I think that Windows handle correctly the `/` and so in case of relative path is the same. If someone specify the root(`c:\`) I suppose the things will change a bit.
We could try to "normalize" all path to `/` handling correctly the rooted path https://learn.microsoft.com/en-us/dotnet/api/system.io.path.ispathrooted?view=net-7.0

**Comment by jakubch1** [comment]
We fixed this. Both path separators `/` and `\` are supported on all OSes.
