### ISSUE TITLE
Code Coverage should not be checking the unit test projects themselves for coverage. 

### ISSUE THREAD

**Issue by StingyJack** [microsoft/codecoverage#20]
Running the code coverage option from the test explorer will always display the coverage statistics for unit test assemblies, and this skews the overall results. 

I'm aware that this can be excluded by using a runsettings/testsettings file, but that has become tedious after a hundred or so projects, especially since VS cant associate and remember the test settings file with the solution. The way it requires file naming is also easy to mess up.

There is a request open to permit the [ExcludeFromCodeCoverage] attribute to an assembly, but that is targeted to net core and not net framework. 

Can unit test projects just be removed from the coverage stats by default, and still let those who want this opt in?

**Comment by gioce90** [comment]
> We are considering adding new flag to easily exclude test projects so reopening this issue.

this would be an awesome improvement!

**Comment by jakubch1** [comment]
We have added new flag. In upcoming 17.8 release of our `Microsoft.CodeCoverage` package you can do:
```
dotnet test --collect "Code Coverage;IncludeTestAssembly=false"
```
Name of the flag is consistent with coverlet.

**Comment by gioce90** [comment]
Hi @jakubch1 , `IncludeTestAssembly=false` seems what we needs, thank you. I would ask, there is also a way to exclude also third-part libraries as well?

**Comment by gioce90** [comment]
Hi @jakubch1  , `IncludeTestAssembly=false` seems what we needs, thank you. I would ask, there is also a way to exclude also third-part libraries as well?

**Comment by fhnaseer** [comment]
> Hi @jakubch1 , `IncludeTestAssembly=false` seems what we needs, thank you. I would ask, there is also a way to exclude also third-part libraries as well?

You can exclude these using runsettings file. https://learn.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022#include-or-exclude-assemblies-and-members

**Comment by gioce90** [comment]
Sadly I think that .runsettings file is pure evil :D to manually add and remove lines from that file.... I think that a better out-of-the-box solution can be designed (IMHO)

**Comment by gioce90** [comment]
Interesting. However, why doesn't the code coverage focus on what we are testing as default behavior?

In my company usually we do:
  
```
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/*.csproj'  #or *.sln
    arguments: '--no-restore --configuration $(buildConfiguration) --collect "Code Coverage;IncludeTestAssembly=false"' 
```

or

```
- script: dotnet test MySolutionFolder --configuration $(buildConfiguration) --logger "trx;LogFileName=testresults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults/Coverage/
  displayName: 'dotnet test'
```

With `projects: '**/*.csproj`', or `*.sln`, or with `MySolutionFolder` we already indicate what we want to test.
It would be interesting if the code coverage only focused on these, as default behavior. 

I think Coverlet is already doing something like that: "Coverlet automatically excludes third-party assemblies from the coverage analysis" (https://github.com/coverlet-coverage/coverlet/issues/1164) and [in many other ways](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#excluding-from-coverage)

If there are concerns about breaking changes, perhaps a flag called, for example, `IncludeThirdPartyForCoverage=false` should make sense.
