### ISSUE TITLE
dotnet-coverage not returning errors if tests fails

### ISSUE THREAD

**Issue by midium81** [microsoft/codecoverage#24]
I've recently used this tool to implement code coverage in our builds though Jenkins pipeline.
After some struggle I've got it to work but I've seen that unfortunately the build won't stop in case tests fails as dotnet-coverage looks ignoring it.
The command I've used looks like following:

dotnet-coverage collect -o coverage.xml -f xml dotnet test {path to test}

Build was reporting 
![image](https://user-images.githubusercontent.com/39514370/229108051-5713f62a-77be-47c5-b146-6871a32d9d70.png)

But pipeline execution continued anyway as the result of _dotnet test_ was swallow by dotnet-coverage that was at the end return all was ok.
To void the issue I've got to run tests alone to provoke the eventual fail of the pipeline and then again for the coverage computation. This is obviously not the best as I would expect the coverage collection should fail along with failing tests.

Any idea how to possibly solve this?

Cheers,
Matteo

**Comment by jakubch1** [comment]
Do you use latest version of dotnet-coverage? I see it works correctly:

```
D:\examples\xunitnewdemo> dotnet-coverage collect -f xml "dotnet test D:\examples\xunitnewdemo\bin\Debug\net8.0\xunitnewdemo.dll"
Microsoft (R) Code Coverage Command Line Tool (x64)
Copyright (c) Microsoft Corporation. All rights reserved.

SessionId: 0f9fb2f9-39b1-43a8-9650-0832d1f9ca22
Microsoft (R) Test Execution Command Line Tool Version 17.6.0-preview-20230223-05 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.06]     xunitnewdemo.UnitTest1.Test1 [FAIL]
  Failed xunitnewdemo.UnitTest1.Test1 [6 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 1
Actual:   0
  Stack Trace:
     at xunitnewdemo.UnitTest1.Test1() in D:\examples\xunitnewdemo\UnitTest1.cs:line 8
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - xunitnewdemo.dll (net8.0)
Code coverage results: output.xml.
D:\examples\xunitnewdemo> echo $?
False
```

**Comment by midium81** [comment]
Hello,
thanks for the quick reply, I've installed it inside a docker image we use for builds last Friday using following command:
dotnet tool install --global dotnet-coverage

So I smell this will get latest version. At this point I'm not sure if it is the cake script we use to perform the build that is not able to understand the returned error? This is pretty strange though as in general when a problem raise in the script it stops automatically, will dig a bit on it though just to double check, thanks for the info for now.

Cheers,
Matteo
