### ISSUE TITLE
"Code Coverage" collector not work under some special folder structure

### ISSUE THREAD

**Issue by leolcao** [microsoft/codecoverage#28]
## Description

I find under certain folder structure, the vstest.console.exe with the builtin "Code Coverage" can not collect code coverage and throw the warning/error message:

`Data collect "Code Coverage" message: No code coverage data available. Profiler was not initialized.`

The sample repo to reproduce the bug is hosted in https://github.com/leolcao/vstest-sample.

## Expected behavior

1. want to know and understand the root cause
2. Under any folder structure, vstest.console.exe with "Code Coverage" collector can generate right content of result file.

**Comment by fhnaseer** [comment]
@leolcao What do you mean by the following lines?

> Next step to represent the bug of vstest.console.exe/datacollector.exe is to copy 2 folders into different sub-folders and re-run the vstest.console.exe command.
> x64
> packages

Are you copying only vstest.consol.exe or datacollector.exe?

**Comment by leolcao** [comment]
@fhnaseer I didn't do "copying" stuff, I use the vstest.console.exe from the nuget package, you can see the  https://github.com/leolcao/vstest-sample/blob/main/packages.config

**Comment by fhnaseer** [comment]
> When I re-run above vsteest.console.exe under certain sub-folder, it shows the error and no right content in the coverage.xml file.

What is the exact command line you are trying to execute?

**Comment by leolcao** [comment]
hi @fhnaseer I think I already addressed what I did from my github repo https://github.com/leolcao/vstest-sample

**Comment by fhnaseer** [comment]
I am sorry as I am not able to understand. When you say "copy 2 folders into different sub-folders" what are you copying?
> Next step to represent the bug of vstest.console.exe/datacollector.exe is to copy 2 folders into different sub-folders and re-run the vstest.console.exe command.
> x64
> packages

And for the following line, do you mean you are in `$(solutionDir)aaaaaaaaaaaaaaaaaaaaa` folder and calling `(Path to packages\vstest.consol.exe)` `(Path to x64\Release/GoogleTest.Tests.exe)` `/TestAdapterPath:(path to packages\googletestadopter`?
> When I re-run above vsteest.console.exe under certain sub-folder

**Comment by leolcao** [comment]
hi @fhnaseer I already updated the README from my demo repo, pls looking at the updates, hope it is clear enough for u. Btw, do u already get the main points from my repo about the issue although missing some details?

**Comment by leolcao** [comment]
> I am sorry as I am not able to understand. When you say "copy 2 folders into different sub-folders" what are you copying?
> 
> > Next step to represent the bug of vstest.console.exe/datacollector.exe is to copy 2 folders into different sub-folders and re-run the vstest.console.exe command.
> > x64
> > packages
> 
> And for the following line, do you mean you are in `$(solutionDir)aaaaaaaaaaaaaaaaaaaaa` folder and calling `(Path to packages\vstest.consol.exe)` `(Path to x64\Release/GoogleTest.Tests.exe)` `/TestAdapterPath:(path to packages\googletestadopter`?
> 
> > When I re-run above vsteest.console.exe under certain sub-folder

Copying folders is just to re-run command:

```
packages/Microsoft.TestPlatform.17.5.0/tools/net462/Common7/IDE/Extensions/TestPlatform/vstest.console.exe x64/Release/GoogleTest.Tests.exe /TestAdapterPath:packages/GoogleTestAdapter.0.18.0/build/_common /Collect:"Code Coverage;Format=xml;CoverageFileName=coverage" /ResultsDirectory:build/unit-test
```

in different subfolder, you see, this command depends on the packages and x64 folder and related files

**Comment by fhnaseer** [comment]
I tried different combinations, and I am able to generate coverage file always.
1: Default
Executing Directory: $(solutionDir)
packages dir: $(solutionDir)\packages
x64 dir: $(solutionDir)\x64

2: Executing command from another directory
Executing Directory: $(solutionDir)\aaaaaaaaaaaaaaaaaaaaa 
packages dir: $(solutionDir)\packages
x64 dir: $(solutionDir)\x64

3: Everything in aaaaaaaaaaaaaaaaaaaaa  folder
Executing Directory: $(solutionDir)\aaaaaaaaaaaaaaaaaaaaa 
packages dir: $(solutionDir)\aaaaaaaaaaaaaaaaaaaaa \packages
x64 dir: $(solutionDir)\aaaaaaaaaaaaaaaaaaaaa \x64

4: packages and x64 in different folders
Executing Directory: $(solutionDir)\aaaaaaaaaaaaaaaaaaaaa 
packages dir: $(solutionDir)\packages
x64 dir: $(solutionDir)\aaaaaaaaaaaaaaaaaaaaa \x64

5: packages and x64 in different folders
Executing Directory: $(solutionDir)\
packages dir: $(solutionDir)\packages
x64 dir: $(solutionDir)\aaaaaaaaaaaaaaaaaaaaa \x64

You mentioned these cases. What is your $(solutionDir)? Is it a big path?
$(solutionDir)aaaaaaaaaaaaaaaaaaaaa: Bad Case
d:\aaaaaaaaaaaaaaaaaaaaa: Good Case

Also, for the problematic case, can you please add `/diag:log.vstest.txt /logger:"console;verbosity=detailed"` to vstest.console.exe command and execute it? It will generate log files starting with `log.vstest.*`. Can you please share these files?

**Comment by leolcao** [comment]
![image](https://github.com/microsoft/codecoverage/assets/539695/0dcea128-1c64-4179-9846-d82f1185b42c)

[log.vstest.datacollector.23-05-24_08-43-46_19533_1.txt](https://github.com/microsoft/codecoverage/files/11549412/log.vstest.datacollector.23-05-24_08-43-46_19533_1.txt)
[log.vstest.host.23-05-24_08-43-46_76045_6.txt](https://github.com/microsoft/codecoverage/files/11549413/log.vstest.host.23-05-24_08-43-46_76045_6.txt)
[log.vstest.txt](https://github.com/microsoft/codecoverage/files/11549414/log.vstest.txt)

**Comment by fhnaseer** [comment]
Thanks for the logs. I see that a coverage file (coverage.xml) is generated. Does it contain right coverage information or is it empty?

**Comment by leolcao** [comment]
> Thanks for the logs. I am able to reproduce this. It seems like issue is with the path limit. I am investigating this and will update you.

Great ~ hope this issue can be fixed soon

**Comment by fhnaseer** [comment]
It fails when we are trying to load a dll which exceeds the path limit. There are two issues here.

1. Actual path size exceeds the limit. In this case we fail. https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later
2. Actual path size is in the limit but exceeds due to relative characters in the path "..\..\..". This issue is fixed and will be available in the next release.
