### ISSUE TITLE
How to present code coverage report on Azure DevOps

### ISSUE THREAD

**Issue by wli3** [microsoft/codecoverage#29]
_From @SergiyKostenko on Sunday, March 22, 2020 4:25:08 PM_

Hello,

Is there way to present code coverage report using DotNetCoreCLI@2 test command? 
Documentation (https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=yaml#collect-code-coverage) says
 **The .coverage file can be downloaded from the build summary for viewing in Visual Studio.** Howewer, it is not handy to download it. I would prefer to see it on tab? Is it possible with default dotnet cli?
![image](https://user-images.githubusercontent.com/20420244/77254623-e0ad2c00-6c6a-11ea-9afe-8ce1a18b2c8a.png)

_Copied from original issue: dotnet/sdk#10962_

**Comment by gioce90** [comment]
is this issue closed now?
