### ISSUE TITLE
Azure CI pipelines becomes unreliable after update to 17.6.2 (17.6.1 and 17.6.0 were fine)

### ISSUE THREAD

**Issue by vbaderks** [microsoft/codecoverage#34]
## Description

I have an open source project that wraps a native image codec and is available as NuGet component.
https://github.com/team-charls/charls-native-dotnet

This project targets Windows, Linux and macOs for .NET Framework 4.8, .NET 6.0 and .NET 7.0.
It has a test project based on NUnit and a Dependabot action configured to update the dependencies.

Dependabot created a pull request to update Microsoft.NET.Test.Sdk from 17.6.1 to 17.6.2.
With 17.6.2 some unit test tasks often fail on the Azure CI build pipeline.

## Steps to reproduce

1. Checkout https://github.com/team-charls/charls-native-dotnet
2. Create a branch
3. Update Microsoft.NET.Test.Sdk from 17.6.1 to 17.6.2
4. Check in the branch and create a PR.

## Expected behavior

All test pass reliable.

## Actual behavior

The unit test process for .NET 6.0 and .NET 7.0 on Window fail. It is mostly the release x86 project.
A re-run may sometimes work and all test pass then.
The Linux, macOS and .NET Framework 4.8 configuration all work fine with 17.6.2.
Older versions: v17.6.0 and v17.6.1 were also working fine.

## Diagnostic logs

The PR of dependabot can be found at:
https://github.com/team-charls/charls-native-dotnet/pull/52
and the several build attempts and log are at:
https://dev.azure.com/team-charls/charls-native-dotnet/_build?definitionId=4

## Environment

The environment on which the tests are failing is the standard "windows-latest" VM image of the Azure CI pipeline.

Building locally and running the tests with:
vstest.console.exe CharLS.Native.Test.dll --Framework:".NETCoreApp,Version=v7.0" --Platform:x86 --Parallel /EnableCodeCoverage
works fine. Running in the Visual Studio 2202 17.6 also works fine.

**Comment by vbaderks** [comment]
100% agree that using /PROFILE is a better solution for native DLLs. The used native DLL is included as a git sub-module.
Plan is to enable /PROFILE in the original repository of the native DLL.

**Comment by jakubch1** [comment]
@vbaderks the issue is that in release mode you compile native dlls with optimizations enabled. Our dynamic code coverage is not supported in that scenario.

Created PR to disable native instrumentation on release mode: https://github.com/team-charls/charls-native-dotnet/pull/55/files. It also enables coverage on linux and macOS.
