### ISSUE TITLE
VSTest Uploading .coverage files without .coverage extension

### ISSUE THREAD

**Issue by danieloh1** [microsoft/codecoverage#36]
## Description
The coverage file uploaded by VSTest 17.6.2 and 17.6.0 is uploading without extension. 

## Steps to reproduce
&'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe' D:\Workspace\Networking-nfv\out\\debug-x64\GatewayBillingV3.UnitTests\GatewayBillingV3.UnitTests.dll /Platform:x64 /framework:net462 /Diag:C:\Users\danieloh\AppData\Local\Temp\VstsLocalTestRun_qoyto2hu.tsg\GatewayBillingV3.UnitTests_GatewayManager_DiagonasticsFile.log /TestCaseFilter:TestCategory=GatewayManager /ResultsDirectory:C:\Users\danieloh\AppData\Local\Temp\VstsLocalTestRun_qoyto2hu.tsg /Logger:"trx;LogFileName=Results_GatewayBillingV3.UnitTests_GatewayManager_2023-06-28_08_07_20.trx" /Settings:D:\Workspace\Networking-nfv\src\unittest\scripts\coverage.runsettings /inIsolation

## Expected behavior
This should run our tests and produce a coverage file which we open using Start-Process <path_to_coveragefile>. We aren't sure which VSTest version this started happening but noticed that at least VSTest 17.6.0 it is broken. 

Below screenshot is an example from VSTest 16.11.0 (shipped with latest VS2019)
![image](https://github.com/microsoft/vstest/assets/105062615/3e1e8622-3f3e-4927-86f6-fbc5a39e66e2)

## Actual behavior
The coverage file is generated and uploaded without any extension
![image](https://github.com/microsoft/vstest/assets/105062615/18c198ef-d0e7-4c0a-a18f-ce48efff824a)
![image](https://github.com/microsoft/vstest/assets/105062615/0eeb124c-b78e-4211-8db6-0541f699085b)

## Environment
Windows 11
VSTest 17.6.2 (version shipped with VS 17.6.4)

**Comment by jakubch1** [comment]
@danieloh1 you can try to use some preview version from here: https://dev.azure.com/dnceng/public/_artifacts/feed/test-tools/NuGet/Microsoft.TestPlatform/versions/17.8.0-preview-23328-02
You can plug it in into your pipelines using this: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/visual-studio-test-platform-installer-v1?view=azure-pipelines
