### ISSUE TITLE
Difference in coverage results between Windows and Linux 

### ISSUE THREAD

**Issue by ArturDorochowicz** [microsoft/codecoverage#37]
I'm getting different coverage results between Windows and Linux.

In a .net solution with references: `Test Project` -> `ProjectA` -> `Project B`, if tests in `Test Project` don't exercise anything from `Project B`, then on Linux `Project B` is not included in coverage results, but it is included (with 0 coverage as expected) when run on Windows. 

I've checked this with .Net 7 and Microsoft.NET.Test.Sdk 17.5.0, as well as with .Net 6 and Microsoft.NET.Test.Sdk 17.6.3.

I'm attaching a tiny solution (projects: Tests -> Console -> Library) that shows the problem [Project.zip](https://github.com/microsoft/codecoverage/files/12005675/Project.zip). For this solution I get (note missing library.dll in Linux results):
on Linux:
![linux](https://github.com/microsoft/codecoverage/assets/482931/aeed4369-280e-4f6e-a2ea-b7bac6fa52c5)
on Windows:
![windows](https://github.com/microsoft/codecoverage/assets/482931/0b19cc74-8f28-460d-adb1-1b23b7d2c17b)

In both cases the coverage was obtained with: `dotnet test --collect "Code Coverage"`

**Comment by jakubch1** [comment]
I've fixed issue. It will be available in 17.8.0 release. If you want you can use preview package: https://dev.azure.com/dnceng/public/_artifacts/feed/test-tools/NuGet/Microsoft.NET.Test.Sdk/overview/17.8.0-preview-23363-04
