### ISSUE TITLE
Code coverage results don't include net462 TFMs

### ISSUE THREAD

**Issue by geeknoid** [microsoft/codecoverage#38]
In https://github.com/dotnet/extensions, the coverage report we are getting doesn't factor in data for the net462 TFM. We run our tests for a bunch of TFMs and the coverage report shows that the else branch of code that does:

```
#fi NETCOREAPP_3_1_OR_GREATER
// shows as covered
#else
// shows as not-covered
#endif
```

is not covered even though the tests definitely cover that code. I don't know if you have access to this, but here's a coverage report that shows this: https://dev.azure.com/dnceng-public/public/_build/results?buildId=336868&view=codecoverage-tab. The Redactor type in the Microsoft.Extensions.Compliance.Abstractions DLL in particular.

Is this is a known issue/limitation, or do we need to do something special to make this work?

Here's our config file in case that's the problem.

```xml
<?xml version="1.0" encoding="utf-8"?>
<Configuration>
  <Format>cobertura</Format>
  <CodeCoverage>

    <ModulePaths>
      <Include>
        <ModulePath>.*Microsoft.AspNetCore\.[^/\\]+\.dll$</ModulePath>
        <ModulePath>.*Microsoft.Extensions\.[^/\\]+\.dll$</ModulePath>
        <ModulePath>.*Microsoft.Gen\.[^/\\]+\.dll$</ModulePath>
        <ModulePath>.*System\.Cloud\.[^/\\]+\.dll$</ModulePath>
      </Include>
      <Exclude>
        <ModulePath>.*tests\.dll</ModulePath>
        <ModulePath>.*xunit.*</ModulePath>
        <ModulePath>.*moq.*</ModulePath>
      </Exclude>
    </ModulePaths>

    <!-- Match attributes on any code element: -->
    <Attributes>
      <Exclude>
        <!-- Don't forget "Attribute" at the end of the name -->
        <Attribute>^System\.Diagnostics\.DebuggerHiddenAttribute$</Attribute>
        <Attribute>^System\.Diagnostics\.DebuggerNonUserCodeAttribute$</Attribute>
        <Attribute>^System\.CodeDom\.Compiler\.GeneratedCodeAttribute$</Attribute>
        <Attribute>^System\.Diagnostics\.CodeAnalysis\.ExcludeFromCodeCoverageAttribute$</Attribute>
      </Exclude>
    </Attributes>

    <!-- When set to True, dynamic native instrumentation will be enabled. -->
    <EnableDynamicNativeInstrumentation>false</EnableDynamicNativeInstrumentation>
    <!-- When set to True, instrumented binaries on disk are removed and original files are restored. -->
    <EnableStaticNativeInstrumentationRestore>false</EnableStaticNativeInstrumentationRestore>
    <EnableStaticNativeInstrumentation>false</EnableStaticNativeInstrumentation>
    <UseVerifiableInstrumentation>false</UseVerifiableInstrumentation>

  </CodeCoverage>
</Configuration>
```

Thanks.

@RussKie

AB#1866670

**Comment by fhnaseer** [comment]
@geeknoid It seems like a merge issue. Can you please provide me coverage report for net462 and netcore3.1 for this project?

**Comment by fhnaseer** [comment]
@geeknoid Can you please add `-l coverage.log -ll Verbose` arguments to `dotnet-coverage collect` and share log file?

**Comment by geeknoid** [comment]
@RussKie Can you follow-up on this for me please?

**Comment by RussKie** [comment]
I added th

> @geeknoid Martin Taillefer FTE Can you please add `-l coverage.log -ll Verbose` arguments to `dotnet-coverage collect` and share log file?

I added these settings and ran a build. You can find the logs (for both Windows and Linux) [here](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341504&view=artifacts&type=publishedArtifacts): 
![image](https://github.com/microsoft/codecoverage/assets/4403806/507ecfca-96db-4a61-9bb8-5e724732ac2d)

**Comment by fhnaseer** [comment]
I looked into the logs and coverage files. For the coverage file generated against windows, hits=0 for net462 lines.
![image](https://github.com/microsoft/codecoverage/assets/1503766/68c61d4a-30da-4bb7-8f92-21340bf4e13e)


I tried to repro this locally, but I was able to get coverage correctly.
![image](https://github.com/microsoft/codecoverage/assets/1503766/9a856d5e-d71f-43c2-b89a-010ba52d829a)

I see that you are using dotnet-coverage 17.7.1 version. I would suggest using latest version 17.8.0 and check the results.

**Comment by RussKie** [comment]
I updated the tool to 17.8 and re-ran the build. The logs are here: https://dev.azure.com/dnceng-public/public/_build/results?buildId=344356&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by RussKie** [comment]
@geeknoid which API can we look at to verify to coverage?

**Comment by geeknoid** [comment]
You can look at Microsoft.Extensions.Compliance.Abstractions. Sadly, using the latest version didn't help.

**Comment by fhnaseer** [comment]
Can we do two more things?
1. Run tests only for Microsoft.Extensions.Compliance.Abstractions test (only net462) and see results.
2. Run tests only for Microsoft.Extensions.Compliance.Abstractions test (all TFMs) and see results.

**Comment by RussKie** [comment]
Here's a [build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347345&view=results) that only changes dotnet-coverage version to 17.8.0. Microsoft.Extensions.Compliance.Abstractions coverage is reported at 91.1%.
This [build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347344) is on top of the previous and only builds and tests Microsoft.Extensions.Compliance.Abstractions. The coverage is reported at 100%. The logs are available as well:
![image](https://github.com/microsoft/codecoverage/assets/4403806/27980513-7aa7-405a-930f-434ef0bf472b)

@fhnaseer I'm going OOF, but you can to repro this locally:

<details>
<summary>Local repro steps</summary>


To build and test only Microsoft.Extensions.Compliance.Abstractions for all TFMs:
```
git clone https://github.com/dotnet/extensions.git test
cd test
git switch RussKie-patch-1
./build.cmd -vs Microsoft.Extensions.Compliance.Abstractions -nolaunch
./build.cmd -restore -build -testCoverage
```

Only test for a specific TFM you need to tweak the [build script](https://github.com/dotnet/extensions/blob/5c9ce6ea853aaa48b1e4ad79816e1bd48accfe30/eng/build.ps1#L199):
```diff
diff --git a/eng/build.ps1 b/eng/build.ps1
index f92c89ed5a..e7072dbbd8 100644
--- a/eng/build.ps1
+++ b/eng/build.ps1
@@ -196,7 +196,7 @@ if ($testCoverage) {
     $testResultPath = "./artifacts/TestResults/$configuration";
 
     # Run tests and collect code coverage
-    ./.dotnet/dotnet dotnet-coverage collect --settings ./eng/CodeCoverage.config --output $testResultPath/local.cobertura.xml "build.cmd -test -configuration $configuration -bl:`$$binaryLog"
+    ./.dotnet/dotnet dotnet-coverage collect --settings ./eng/CodeCoverage.config --output $testResultPath/local.cobertura.xml "build.cmd -test -configuration $configuration /p:TestTargetFrameworks=net462 -bl:`$$binaryLog"
```

The run again (no need to restore or re-build again):
```
./build.cmd -testCoverage
```

</details>

**Comment by fhnaseer** [comment]
@RussKie I tried to repro it. I found out that tests are not executed for net462. Since no tests are executed, hence we get zero coverage.

![image](https://github.com/microsoft/codecoverage/assets/1503766/8d9bc7e2-e9c0-43b0-9157-bc6c880e419c)

I tried to do simple dotnet test Microsoft.Extensions.Compliance.Abstractions.Tests.dll, and I received this.

```
Test run for D:\Issues\Net462\extensions\artifacts\bin\Microsoft.Extensions.Compliance.Abstractions.Tests\Debug\net462\Microsoft.Extensions.Compliance.Abstractions.Tests.dll (.NETFramework,Version=v4.6.2)
Microsoft (R) Test Execution Command Line Tool Version 17.7.0-preview-23317-01+919ec8358820228cc5fa77ef000051c1d6875399 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:04.98] Skipping: Microsoft.Extensions.Compliance.Abstractions.Tests (could not find dependent assembly 'Microsoft.Extensions.Compliance.Abstractions.Tests, Version=8.0.0')
No test is available in D:\Issues\Net462\extensions\artifacts\bin\Microsoft.Extensions.Compliance.Abstractions.Tests\Debug\net462\Microsoft.Extensions.Compliance.Abstractions.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

**Comment by jakubch1** [comment]
@RussKie @geeknoid I think you should add option to fail if no tests executed: `<TreatNoTestsAsError>true</TreatNoTestsAsError>`
https://github.com/microsoft/vstest/issues/2247

**Comment by RussKie** [comment]
> I tried to do simple dotnet test Microsoft.Extensions.Compliance.Abstractions.Tests.dll, and I received this.

I tried that too, and it looks like it's working for me:
```powershell
PS> git clean -xdf
PS> .\build.cmd -restore -build -c Release
PS> pushd .\artifacts\bin\Microsoft.Extensions.Compliance.Abstractions.Tests\Release\net462
PS> dotnet test Microsoft.Extensions.Compliance.Abstractions.Tests.dll

Microsoft (R) Test Execution Command Line Tool Version 17.7.0-preview-23317-01+919ec8358820228cc5fa77ef000051c1d6875399 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:    38, Skipped:     0, Total:    38, Duration: 78 ms - Microsoft.Extensions.Compliance.Abstractions.Tests.dll (net462)
```

What am I missing?

**Comment by fhnaseer** [comment]
I checked logs for net462 test projects. No tests are being discovered with identical message. https://dev.azure.com/dnceng-public/public/_build/results?buildId=363074&view=artifacts&pathAsName=false&type=publishedArtifacts

=== COMMAND LINE === 
"D:\a\_work\1\s\.dotnet\dotnet.exe" test D:\a\_work\1\s\artifacts\bin\Microsoft.Extensions.Compliance.Abstractions.Tests\Release\net462\Microsoft.Extensions.Compliance.Abstractions.Tests.dll --logger:"console;verbosity=normal" --logger:"trx;LogFileName=Microsoft.Extensions.Compliance.Abstractions.Tests_net462_x64.trx" --logger:"html;LogFileName=Microsoft.Extensions.Compliance.Abstractions.Tests_net462_x64.html" "--ResultsDirectory:D:\a\_work\1\s\artifacts\TestResults\Release" "--Framework:.NETFramework,Version=v4.6.2"  --blame --blame-crash --blame-crash-dump-type full --blame-hang --blame-hang-dump-type full --blame-hang-timeout 6m 
Microsoft (R) Test Execution Command Line Tool Version 17.7.0-preview-23317-01+919ec8358820228cc5fa77ef000051c1d6875399 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Blame: Attaching crash dump utility to process testhost (3352).
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit Desktop .NET 4.0.30319.42000)
**[xUnit.net 00:00:00.68] Skipping: Microsoft.Extensions.Compliance.Abstractions.Tests (could not find dependent assembly 'Microsoft.Extensions.Compliance.Abstractions.Tests, Version=8.0.0')
No test is available in D:\a\_work\1\s\artifacts\bin\Microsoft.Extensions.Compliance.Abstractions.Tests\Release\net462\Microsoft.Extensions.Compliance.Abstractions.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.**
Data collector 'Blame' message: procdump64.exe could not be found, please make sure that the executable is available on PATH. Alternatively set PROCDUMP_PATH environment variable to a directory that contains procdump64.exe executable.
Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.

Results File: D:\a\_work\1\s\artifacts\TestResults\Release\Microsoft.Extensions.Compliance.Abstractions.Tests_net462_x64.trx
Html test results file : D:\a\_work\1\s\artifacts\TestResults\Release\Microsoft.Extensions.Compliance.Abstractions.Tests_net462_x64.html
Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

**Comment by RussKie** [comment]
We've upgraded to the latest 17.8.2, and we're still seeing the issue.

If we run collect the coverage only for the project - it's reported correctly for both net462 and .NET TFMs:
![image](https://github.com/microsoft/codecoverage/assets/4403806/ac84d06f-a587-455f-b118-16b945268e2c)
https://dev.azure.com/dnceng-public/public/_build/results?buildId=372440&view=codecoverage-tab

However, when we build the whole solution, the net462 isn't getting the coverage reported:
![image](https://github.com/microsoft/codecoverage/assets/4403806/74549b54-c99a-46ad-856c-09aad9069522)
https://dev.azure.com/dnceng-public/public/_build/results?buildId=371922&view=codecoverage-tab

The same code, the only difference is the number of projects in the solution.

**Comment by fhnaseer** [comment]
@RussKie Issue is not with the coverage report. When you run tests for all projects/TFMs, then tests for net462 are not executed.

If you open logs for net462 test projects (Microsoft.Extensions.Compliance.Abstractions.Tests_net462_x64.log, Microsoft.AspNetCore.Telemetry.Tests_net462_x64.log, etc.) you will see same error message. https://dev.azure.com/dnceng-public/public/_build/results?buildId=371922&view=artifacts&pathAsName=false&type=publishedArtifacts

[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit Desktop .NET 4.0.30319.42000)
[xUnit.net 00:00:00.80] **Skipping: Microsoft.Extensions.Compliance.Abstractions.Tests (could not find dependent assembly 'Microsoft.Extensions.Compliance.Abstractions.Tests, Version=8.0.0')**
**No test is available in D:\a\_work\1\s\artifacts\bin\Microsoft.Extensions.Compliance.Abstractions.Tests\Release\net462\Microsoft.Extensions.Compliance.Abstractions.Tests.dll**. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

**Comment by RussKie** [comment]
Thank you for pointing this, but could you help us understand why this is happening?

The test assembly is there [according to the logs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374064&view=logs&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589&t=2917e7a9-bb9d-585b-890e-1ad69b6f3f65&l=124):
![image](https://github.com/microsoft/codecoverage/assets/4403806/f17622ed-e920-44b7-9787-c0d49ac110f1)

The binlog contains the same information too:
![image](https://github.com/microsoft/codecoverage/assets/4403806/326b9fc6-fd68-46e7-bbae-b68efc37e5d9)

**Comment by fhnaseer** [comment]
Test assembly is produced and is executed as well, but test runner is not able to discover tests. It seems like building all projects/TFMs together do something with dll version number **(could not find dependent assembly 'Microsoft.Extensions.Compliance.Abstractions.Tests, Version=8.0.0')**. Are you aware of something that happens with all projects build vs one project build only?
It will be good to get contents of `D:\a_work\1\s\artifacts\bin\Microsoft.Extensions.Compliance.Abstractions.Tests\Release\net462` for both working and failing case and compare. And we can also ask xUnit. Maybe they can help why tests are not being discovered in this case.

**Comment by RussKie** [comment]
After testing random ideas, it looks like the key factor in whether the .NET Framework tests are executed or not is the presence of a ".sln" file. 
We don't have a solution file, and use https://github.com/dotnet/extensions/blob/main/eng/build.proj, which defines which projects we build. In this setup the .NET Framework tests don't appear to get executed.
If we pre-generate a solution file, then the .NET Framework tests get executed as expected.
In both scenarios the test execution command line looks exactly the same, so perhaps there's some MSBuild voodoo that's missing...

**Comment by RussKie** [comment]
I'm going to close this, as this looks more like an MSBuild-related issue then a Code Coverage related.
Thank you for your time and help.

**Comment by RussKie** [comment]
Actually, I don't have permissions to close this, haha. @geeknoid / @fhnaseer please close.
