### ISSUE TITLE
Bug: dotnet-coverage v17.9.0 broke our CI-pipeline

### ISSUE THREAD

**Issue by lindeberg** [microsoft/codecoverage#55]
Our GitHub Actions Workflow containing these steps started failing with
`Error: Process completed with exit code 150.`
now that [dotnet-coverage 17.9.0](https://www.nuget.org/packages/dotnet-coverage/17.9.0) got released.

```
...
runs-on: [self-hosted, linux]
...
 - name: Setup .NET
   uses: actions/setup-dotnet@v3
   with:
     dotnet-version: 7.0.x <--(happens with 6.0.x too)
          
 - name: Add dotnet-tools to PATH
    run: echo "/home/runner/.dotnet/tools" >> "$GITHUB_PATH"

  - name: Merge coverage reports
    run: |
      dotnet tool install --global dotnet-coverage
      cd ${{ env.TEST_RESULTS_PATH }}
      dotnet-coverage merge --output coverage-merged.xml --output-format cobertura --recursive coverage.cobertura.xml

```

![image](https://github.com/microsoft/codecoverage/assets/15940340/678983b3-ba82-4c83-8135-cef5a5afa205)
was successful with 17.8.6:
![image](https://github.com/microsoft/codecoverage/assets/15940340/abda5ce7-82c7-4b89-bcab-83cb6048a36d)

We are using this with a dozen workflows and would prefer not to specify the old version in all of them.

**Comment by mhsFlairs** [comment]
+1

**Comment by iamkinetic** [comment]
We have the same problem with our GitLab CI pipelines.

**Comment by olegpuz** [comment]
same here. pls revert latest version to 17.8.6, because current one is broken!

**Comment by mickvdv** [comment]
Workaround is adding --version 17.8.6 to the dotnet tool install command:

`dotnet tool install --global dotnet-coverage --version 17.8.6`

**Comment by jakubch1** [comment]
We have unlisted 17.9.0 version.

**Comment by lindeberg** [comment]
@jakubch1 Not sure how unlisting works, but pipeline is still fetching 17.9.

**Comment by jakubch1** [comment]
17.9.1 with fix was released. Thanks for reporting this
