### ISSUE TITLE
Question about output file coverage.xml

### ISSUE THREAD

**Issue by weucode** [microsoft/codecoverage#62]
When I use `dotnet-coverage collect -f xml dotnet run` to collect the coverage results about my project, there are some skipped functions with the `reason` being `no_symbols`. What does `no_symbols` mean? If I want to collect the coverage results of the specified .dll file, what should I do?

**Comment by fhnaseer** [comment]
`no_symbols` flag is for dll level. For example if pdb is missing for a specific dll, then we cannot calculate code coverage against it.

If you are seeing it on function level, then can you please send coverage report and dll + pdb?

**Comment by weucode** [comment]
Thanks! That is enough! I added the .pdb file for the specific .dll file so that I can get code coverage of this .dll file.
