### ISSUE TITLE
Code Coverage sometimes treats Moq's Mock.Verify as partial coverage

### ISSUE THREAD

**Issue by johnthcall** [microsoft/codecoverage#7]
## Description
Even simple tests with Moq's Mock.Verify there are cases where the last lines of the test are "partially covered" and there are unknown blocks which are "not covered"
![image](https://user-images.githubusercontent.com/23224070/214366716-d816e31f-07c2-46f5-a64b-b28762728dc1.png)

## Steps to reproduce

Run code coverage on the following:
```
[TestMethod]
        public void Test()
        {
            var moq = new Mock<IAsyncDisposable>();
            moq.Verify(m => m.DisposeAsync(), Times.Never);
            moq.Verify(m => m.DisposeAsync(), Times.Never);
        }
```    

## Expected behavior

I would expect for this simple of a test to have 100% line and block coverage.

## Actual behavior

One line and two blocks are partially covered and it appears both are in the second of a duplicated line.

## Diagnostic logs
[log.txt](https://github.com/microsoft/vstest/files/10492642/log.txt)

## Environment

Windows 11, Visual Studio Enterprise 17.4.1

**Comment by johnthcall** [comment]
@fhnaseer The following coverage is from VisaulSTudio 17.5.0 running .net 7 with moq 4.17.1. It also had the same result with moq 4.18.4.
[TestCoverage.zip](https://github.com/microsoft/codecoverage/files/10818360/TestCoverage.zip)

**Comment by johnthcall** [comment]
@fhnaseer Is it possible it is because there is a block for handling if the verifies fail? Here it intentionally fails and the only untested line is the "ret" one.
![image](https://user-images.githubusercontent.com/23224070/221029612-9200a567-309f-430b-8234-bdb5d9266ba1.png)

**Comment by fhnaseer** [comment]
> @fhnaseer Is it possible it is because there is a block for handling if the verifies fail? Here it intentionally fails and the only untested line is the "ret" one. ![image](https://user-images.githubusercontent.com/23224070/221029612-9200a567-309f-430b-8234-bdb5d9266ba1.png)

Mock adds additional blocks. So, it could be possible that verify fail block is not hit. It's quite strange that you are getting 21 blocks.



> @fhnaseer The following coverage is from VisaulSTudio 17.5.0 running .net 7 with moq 4.17.1. It also had the same result with moq 4.18.4. [TestCoverage.zip](https://github.com/microsoft/codecoverage/files/10818360/TestCoverage.zip)

Can you please send .coverage file instead? It should be present in TestResults folder. Or you can send me your whole project.

Also, can you please execute the following command on your test project and open generated coverage file in visual studio?
`dotnet test --collect "Code Coverage"`

**Comment by johnthcall** [comment]
Here is the original code with the coverage file 
[ClassLibrary1.zip](https://github.com/microsoft/codecoverage/files/10826482/ClassLibrary1.zip)

**Comment by fhnaseer** [comment]
I see that the issue is with language version.

With <LangVersion>10.0</LangVersion>
![image](https://user-images.githubusercontent.com/1503766/221548480-6660614a-def6-4536-a805-067ad7c38d38.png)

With <LangVersion>11.0</LangVersion>
![image](https://user-images.githubusercontent.com/1503766/221548651-d374893d-331d-4ece-9ccd-f7178b7fb016.png)

11.0 is adding more blocks for mock verification.

**Comment by johnthcall** [comment]
@fhnaseer It appears the reason is that in version 11 it is doing a check that Times.Never (as a function) is non-null and if it isn't it appears to be skipping some code:
![image](https://user-images.githubusercontent.com/23224070/221672760-7c8971f6-fa99-4d15-9213-46b72d9daef5.png)
I changed the `Times.Never` from a function to an actual times instance `Times.Never()` and now get complete converage:
![image](https://user-images.githubusercontent.com/23224070/221672963-7c8c5c86-60c9-4574-b01a-a904dd580778.png)

**Comment by fhnaseer** [comment]
Yes. I found the same reason as well. Times.Never is adding null condition.
```
	Func<Times> func = <>O.<0>__Never;
	if (func == null)
		func = Times.Never;
```
So for the second call, func is not null and hence that block is not covered. And it seems like Times.Never() fixes the issue.
