### ISSUE TITLE
Dapper and FakeItEasy are presented as separate projects

### ISSUE THREAD

**Issue by x-danma** [microsoft/codecoverage#78]
# Problem

I have a dotnet api that uses dapper in my api project, and FakeItEasy as a test framwork in my test projects. But those get separate coverage results like so:
![image](https://github.com/microsoft/codecoverage/assets/14817492/ac66f3a8-3d39-443a-ada1-3fce270e4d04)

## Expected Behaviour
Only my main csproj project (along with the test projects themselves should be covered), not Dapper and FakeItEasy as they are simple dependencies.

- Is this maybe something wrong with my solution setup?
- Has anyone else encountered this problem?
  - If not, I will make a public repo to replicate this problem.

## Versions
- "Dapper" Version="2.0.123" (referenced from api-project)
- "FakeItEasy" Version="7.2.0" (referenced from test-project)
- "Microsoft.CodeCoverage" Version="17.8.0" (referenced from api-project only) 
- Dotnet 6

By the way, I got here because of your blog on `devblogs.microsoft.com`.

**Comment by fhnaseer** [comment]
Please refer to this scenario to exclude third party dependencies in the coverage report. https://github.com/microsoft/codecoverage/blob/main/samples/Calculator/scenarios/scenario06/README.md

**Comment by jakubch1** [comment]
We will probably work on some automatic exclusion as part of: https://github.com/microsoft/codecoverage/issues/72
Closing this one

**Comment by x-danma** [comment]
Thank you! Scenario6 fixed it!
