### ISSUE TITLE
`package.branch-rate="0"` even though `class.branch-rate!="0"`

### ISSUE THREAD

**Issue by RussKie** [microsoft/codecoverage#9]
dotnet-coverage: v17.6.6
Microsoft.CodeCoverage: 17.6.0-preview-20230221-02

After switching to `dotnet code-coverage "command"` I'm getting our code coverage validation failing which worked when I collected the coverage via `dotnet test --collect:... --test-adapter-path:...`.
For example:
![image](https://user-images.githubusercontent.com/4403806/221717989-f9f04c0e-ea79-43bf-97bb-2e375a96bfc3.png)

This looks wrong to me, should `package.branch-rate="1"` in this case? Stats collected the old way (i.e., `dotnet test --collect...`) and then merged together resulted in the following (for the same package, I stripped the package name and file names):
![image](https://user-images.githubusercontent.com/4403806/221724347-8e27203e-8835-4a0c-a02f-52a7ce013e02.png)

You can grab the new coverage.cobertura.xml [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=2124110&view=artifacts&pathAsName=false&type=publishedArtifacts) (under "drop").
The old merged covertura.xml can be downloaded from [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=2120222&view=artifacts&pathAsName=false&type=publishedArtifacts). 

I also tried dotnet-coverage 17.4.2 and 17.5.2 and few different version of Microsoft.CodeCoverage, and results seem to be the same.

**Comment by jakubch1** [comment]
@fhnaseer please check overall statistics calculation.

**Comment by jakubch1** [comment]
@RussKie please check 17.6.7. I hope issue is fixed.
