### ISSUE TITLE
No coverage from service

### ISSUE THREAD

**Issue by KavenBreton-eaton** [microsoft/codecoverage#96]
Platform: Windows
.Net version: .NET Framework 4.8

We want to get coverage data from our system tests but are unable to get any coverage from our services or any process launched by them.

`dotnet-coverage collect -id "Project.CodeCoverage" --server-mode --include-files "*Project.*.dll" --output "C:\dev\localCoverageTest\project.coverage" --log-file "C:\dev\localCoverageTest\dotnet-coverage-collect.log" --log-level "Verbose"`

We are calling the _collect_ from a powershell script that then start the services and perform our automated tests. The PowerShell ISE is running as admin with the current user while the service might be running with Local System.

Is there something special that should be done in this particular case?

**Comment by fhnaseer** [comment]
Can you please share log files?
Also, how are you shutting down dotnet-coverage collect session?

**Comment by KavenBreton-eaton** [comment]
This is a Windows desktop service. Not IIS.
Sorry for the logs, I sent you the .coverage file instead. Here is the right one 
[dotnet-coverage-collect.log](https://github.com/microsoft/codecoverage/files/14179898/dotnet-coverage-collect.log)

**Comment by fhnaseer** [comment]
`--include-files "*Project.*.dll"`
From the logs, it was not able to find any matching dlls for the given pattern. We use globing pattern to find dlls. https://learn.microsoft.com/en-us/dotnet/core/extensions/file-globbing
Please check your pattern and see if it works.

**Comment by KavenBreton-eaton** [comment]
I am getting the same result just by using "*.dll" for instance.

**Comment by fhnaseer** [comment]
Do you pdbs present in the matching dll folder? Any change in the log files?
To be sure, when you specify `--include-files ".*.dll"`, it is going to search dlls present only in the current directory.

**Comment by KavenBreton-eaton** [comment]
Do you pdbs present in the matching dll folder? Yes. Symbols are present alongside the binaries.
I am not sure of what you mean by you second sentence. When I specify files to include, it is not going to try and instrument any dll that match that pattern on the machine?

**Comment by fhnaseer** [comment]
No, it will not look for dlls on the machine. It will look only in the working directory.
For example, if you are running it from `C:\code\src` then it will only look for files in that folder for instrumentation.

`--include-files` argument can be provided more than once. For example,
`dotnet-coverage collect --server-mode --session-id coverageSession --include-files d:\server\*.dll --include-files d:\client\*.dll`
In this case we will instrument all dlls in `d:\server` and `d:\client` folders for coverage collection.

**Comment by KavenBreton-eaton** [comment]
Ok. Thanks for your input. I did not know it was working like this. From a quick test, I was able to get some coverage information.
